pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
pos(drinks(t,_)).
