pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,f)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
pos(bupa(t,t)).
